import {
  FileText,
  Heart,
  Star,
  Home,
  Settings,
  Search,
  Mail,
  Phone,
  Calendar,
  Clock,
  Camera,
  Image,
  Video,
  Music,
  Mic,
  Headphones,
  Monitor,
  Smartphone,
  Tablet,
  Laptop,
  Globe,
  Map,
  MapPin,
  Navigation,
  Compass,
  Sun,
  Moon,
  Cloud,
  CloudRain,
  Zap,
  Flame,
  Droplets,
  Wind,
  Snowflake,
  TreePine,
  Flower2,
  Leaf,
  Mountain,
  Waves,
  Bug,
  Coffee,
  Utensils,
  Cake,
  Pizza,
  Apple,
  Rocket,
  Plane,
  Car,
  Bike,
  Train,
  Ship,
  Building2,
  Hotel,
  Landmark,
  Church,
  Tent,
  Flag,
  Trophy,
  Medal,
  Target,
  Gamepad2,
  Dumbbell,
  Swords,
  Shield,
  Crown,
  Gem,
  Gift,
  PartyPopper,
  Sparkles,
  Palette,
  Paintbrush,
  Pen,
  Pencil,
  Highlighter,
  BookOpen,
  Book,
  Library,
  GraduationCap,
  Lightbulb,
  BrainCircuit,
  Code,
  Terminal,
  Database,
  Server,
  HardDrive,
  Cpu,
  Wifi,
  Bluetooth,
  Battery,
  Power,
  Lock,
  Unlock,
  Key,
  Eye,
  EyeOff,
  Bell,
  BellRing,
  MessageCircle,
  MessageSquare,
  Send,
  Inbox,
  Archive,
  Trash2,
  FolderOpen,
  Folder,
  File,
  FileCheck,
  FilePlus,
  Clipboard,
  ClipboardList,
  ListTodo,
  CheckSquare,
  SquareCheck,
  CircleCheck,
  CircleX,
  AlertTriangle,
  Info,
  HelpCircle,
  Users,
  UserPlus,
  UserCheck,
  Briefcase,
  BadgeDollarSign,
  Wallet,
  CreditCard,
  Receipt,
  BarChart3,
  PieChart,
  TrendingUp,
  DollarSign,
  Percent,
  Hash,
  AtSign,
  Link,
  ExternalLink,
  Download,
  Upload,
  Share2,
  Repeat,
  Shuffle,
  Play,
  Pause,
  SkipForward,
  Volume2,
  Maximize,
  Minimize,
  Move,
  Grab,
  Hand,
  MousePointer,
  Wand2,
  Scissors,
  Eraser,
  RotateCcw,
  RefreshCw,
  Filter,
  SlidersHorizontal,
  LayoutGrid,
  LayoutList,
  Columns3,
  Rows3,
  Table,
  Kanban,
  PanelLeft,
  ChevronRight,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  CornerDownRight,
  MoveRight,
  ChevronsUp,
  Plus,
  Minus,
  X,
  Check,
  Loader,
  type LucideIcon,
} from "lucide-react";

// --- Icon type detection ---

export function isLucideIcon(value: string): boolean {
  return value.startsWith("lucide:");
}

export function isUrlIcon(value: string): boolean {
  return value.startsWith("http://") || value.startsWith("https://");
}

export function isEmojiIcon(value: string): boolean {
  return !!value && !isLucideIcon(value) && !isUrlIcon(value);
}

export function getLucideIconName(value: string): string {
  return value.replace("lucide:", "");
}

// --- Lucide icon map (static imports for tree-shaking) ---

export const LUCIDE_ICON_MAP: Record<string, LucideIcon> = {
  "file-text": FileText,
  heart: Heart,
  star: Star,
  home: Home,
  settings: Settings,
  search: Search,
  mail: Mail,
  phone: Phone,
  calendar: Calendar,
  clock: Clock,
  camera: Camera,
  image: Image,
  video: Video,
  music: Music,
  mic: Mic,
  headphones: Headphones,
  monitor: Monitor,
  smartphone: Smartphone,
  tablet: Tablet,
  laptop: Laptop,
  globe: Globe,
  map: Map,
  "map-pin": MapPin,
  navigation: Navigation,
  compass: Compass,
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  "cloud-rain": CloudRain,
  zap: Zap,
  flame: Flame,
  droplets: Droplets,
  wind: Wind,
  snowflake: Snowflake,
  "tree-pine": TreePine,
  flower: Flower2,
  leaf: Leaf,
  mountain: Mountain,
  waves: Waves,
  bug: Bug,
  coffee: Coffee,
  utensils: Utensils,
  cake: Cake,
  pizza: Pizza,
  apple: Apple,
  rocket: Rocket,
  plane: Plane,
  car: Car,
  bike: Bike,
  train: Train,
  ship: Ship,
  building: Building2,
  hotel: Hotel,
  landmark: Landmark,
  church: Church,
  tent: Tent,
  flag: Flag,
  trophy: Trophy,
  medal: Medal,
  target: Target,
  gamepad: Gamepad2,
  dumbbell: Dumbbell,
  swords: Swords,
  shield: Shield,
  crown: Crown,
  gem: Gem,
  gift: Gift,
  "party-popper": PartyPopper,
  sparkles: Sparkles,
  palette: Palette,
  paintbrush: Paintbrush,
  pen: Pen,
  pencil: Pencil,
  highlighter: Highlighter,
  "book-open": BookOpen,
  book: Book,
  library: Library,
  "graduation-cap": GraduationCap,
  lightbulb: Lightbulb,
  brain: BrainCircuit,
  code: Code,
  terminal: Terminal,
  database: Database,
  server: Server,
  "hard-drive": HardDrive,
  cpu: Cpu,
  wifi: Wifi,
  bluetooth: Bluetooth,
  battery: Battery,
  power: Power,
  lock: Lock,
  unlock: Unlock,
  key: Key,
  eye: Eye,
  "eye-off": EyeOff,
  bell: Bell,
  "bell-ring": BellRing,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  send: Send,
  inbox: Inbox,
  archive: Archive,
  trash: Trash2,
  "folder-open": FolderOpen,
  folder: Folder,
  file: File,
  "file-check": FileCheck,
  "file-plus": FilePlus,
  clipboard: Clipboard,
  "clipboard-list": ClipboardList,
  "list-todo": ListTodo,
  "check-square": CheckSquare,
  "square-check": SquareCheck,
  "circle-check": CircleCheck,
  "circle-x": CircleX,
  "alert-triangle": AlertTriangle,
  info: Info,
  "help-circle": HelpCircle,
  users: Users,
  "user-plus": UserPlus,
  "user-check": UserCheck,
  briefcase: Briefcase,
  "dollar-sign": BadgeDollarSign,
  wallet: Wallet,
  "credit-card": CreditCard,
  receipt: Receipt,
  "bar-chart": BarChart3,
  "pie-chart": PieChart,
  "trending-up": TrendingUp,
  dollar: DollarSign,
  percent: Percent,
  hash: Hash,
  "at-sign": AtSign,
  link: Link,
  "external-link": ExternalLink,
  download: Download,
  upload: Upload,
  share: Share2,
  repeat: Repeat,
  shuffle: Shuffle,
  play: Play,
  pause: Pause,
  "skip-forward": SkipForward,
  volume: Volume2,
  maximize: Maximize,
  minimize: Minimize,
  move: Move,
  grab: Grab,
  hand: Hand,
  "mouse-pointer": MousePointer,
  wand: Wand2,
  scissors: Scissors,
  eraser: Eraser,
  undo: RotateCcw,
  refresh: RefreshCw,
  filter: Filter,
  sliders: SlidersHorizontal,
  "layout-grid": LayoutGrid,
  "layout-list": LayoutList,
  columns: Columns3,
  rows: Rows3,
  table: Table,
  kanban: Kanban,
  "panel-left": PanelLeft,
  "chevron-right": ChevronRight,
  "arrow-up": ArrowUp,
  "arrow-down": ArrowDown,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  "corner-down-right": CornerDownRight,
  "move-right": MoveRight,
  "chevrons-up": ChevronsUp,
  plus: Plus,
  minus: Minus,
  x: X,
  check: Check,
  loader: Loader,
};

// --- Lucide icons organized by category ---

export const LUCIDE_ICON_CATEGORIES = [
  {
    label: "Documents",
    icons: [
      "file-text", "file", "file-check", "file-plus", "folder", "folder-open",
      "clipboard", "clipboard-list", "book-open", "book", "library",
      "list-todo", "check-square", "square-check",
    ],
  },
  {
    label: "Communication",
    icons: [
      "mail", "send", "inbox", "archive", "message-circle", "message-square",
      "phone", "bell", "bell-ring", "users", "user-plus", "user-check",
      "at-sign", "hash",
    ],
  },
  {
    label: "Media",
    icons: [
      "camera", "image", "video", "music", "mic", "headphones",
      "play", "pause", "skip-forward", "volume", "monitor", "smartphone",
      "tablet", "laptop",
    ],
  },
  {
    label: "Development",
    icons: [
      "code", "terminal", "database", "server", "hard-drive", "cpu",
      "wifi", "bluetooth", "globe", "bug", "brain", "lightbulb",
    ],
  },
  {
    label: "Business",
    icons: [
      "briefcase", "dollar-sign", "wallet", "credit-card", "receipt",
      "bar-chart", "pie-chart", "trending-up", "dollar", "percent",
      "kanban", "target",
    ],
  },
  {
    label: "Creative",
    icons: [
      "palette", "paintbrush", "pen", "pencil", "highlighter",
      "wand", "scissors", "eraser", "sparkles",
    ],
  },
  {
    label: "Objects",
    icons: [
      "home", "building", "hotel", "landmark", "church", "tent",
      "key", "lock", "unlock", "gift", "crown", "gem",
      "trophy", "medal", "flag", "coffee",
    ],
  },
  {
    label: "Nature",
    icons: [
      "sun", "moon", "cloud", "cloud-rain", "zap", "flame",
      "droplets", "wind", "snowflake", "tree-pine", "flower", "leaf",
      "mountain", "waves",
    ],
  },
  {
    label: "Travel",
    icons: [
      "rocket", "plane", "car", "bike", "train", "ship",
      "map", "map-pin", "navigation", "compass",
    ],
  },
  {
    label: "Actions",
    icons: [
      "search", "settings", "filter", "sliders", "download", "upload",
      "share", "link", "external-link", "refresh", "undo",
      "eye", "eye-off", "power", "battery",
    ],
  },
  {
    label: "Fun",
    icons: [
      "heart", "star", "party-popper", "gamepad", "dumbbell",
      "swords", "shield", "graduation-cap", "utensils", "cake",
      "pizza", "apple",
    ],
  },
  {
    label: "Layout",
    icons: [
      "layout-grid", "layout-list", "columns", "rows", "table",
      "panel-left", "maximize", "minimize", "move",
    ],
  },
  {
    label: "Arrows",
    icons: [
      "arrow-up", "arrow-down", "arrow-left", "arrow-right",
      "arrow-up-right", "chevron-right", "chevrons-up",
      "corner-down-right", "move-right",
    ],
  },
  {
    label: "Symbols",
    icons: [
      "plus", "minus", "x", "check", "circle-check", "circle-x",
      "alert-triangle", "info", "help-circle", "loader",
      "hand", "grab", "mouse-pointer",
    ],
  },
];

// --- Expanded emoji data ---

export const EMOJI_DATA = [
  {
    label: "Smileys",
    emojis: [
      "\u{1F600}", "\u{1F603}", "\u{1F604}", "\u{1F601}", "\u{1F606}", "\u{1F605}",
      "\u{1F923}", "\u{1F602}", "\u{1F642}", "\u{1F643}", "\u{1FAE0}", "\u{1F609}",
      "\u{1F60A}", "\u{1F607}", "\u{1F970}", "\u{1F60D}", "\u{1F929}", "\u{1F618}",
      "\u{1F617}", "\u{1F61A}", "\u{1F619}", "\u{1F972}", "\u{1F60B}", "\u{1F61B}",
      "\u{1F61C}", "\u{1F92A}", "\u{1F61D}", "\u{1F911}", "\u{1F917}", "\u{1F92D}",
      "\u{1FAE2}", "\u{1FAE3}", "\u{1F92B}", "\u{1F914}", "\u{1FAE1}", "\u{1F910}",
      "\u{1F928}", "\u{1F610}", "\u{1F611}", "\u{1F636}", "\u{1FAE5}", "\u{1F60F}",
      "\u{1F612}", "\u{1F644}", "\u{1F62C}", "\u{1F62E}\u{200D}\u{1F4A8}", "\u{1F925}",
      "\u{1FAE8}", "\u{1F60C}", "\u{1F614}", "\u{1F62A}", "\u{1F924}", "\u{1F634}",
      "\u{1F637}", "\u{1F912}", "\u{1F915}", "\u{1F922}", "\u{1F92E}", "\u{1F927}",
    ],
  },
  {
    label: "People",
    emojis: [
      "\u{1F44B}", "\u{1F91A}", "\u{270B}", "\u{1F596}", "\u{1FAF1}", "\u{1FAF2}",
      "\u{1FAF3}", "\u{1FAF4}", "\u{1FAF7}", "\u{1FAF8}", "\u{1F44C}", "\u{1F90C}",
      "\u{270C}\uFE0F", "\u{1F91E}", "\u{1FAF0}", "\u{1F91F}", "\u{1F918}", "\u{1F919}",
      "\u{1F448}", "\u{1F449}", "\u{1F446}", "\u{1F447}", "\u{261D}\uFE0F", "\u{1FAF5}",
      "\u{1F44D}", "\u{1F44E}", "\u{270A}", "\u{1F44A}", "\u{1F91B}", "\u{1F91C}",
      "\u{1F44F}", "\u{1F64C}", "\u{1FAF6}", "\u{1F450}", "\u{1F932}", "\u{1F91D}",
      "\u{1F64F}", "\u{270D}\uFE0F", "\u{1F485}", "\u{1F933}", "\u{1F4AA}", "\u{1F9BE}",
      "\u{1F9BF}", "\u{1F9B5}", "\u{1F9B6}", "\u{1F442}", "\u{1F9BB}", "\u{1F443}",
      "\u{1F9E0}", "\u{1FAC0}", "\u{1FAC1}", "\u{1F9B7}", "\u{1F9B4}", "\u{1F440}",
      "\u{1F441}\uFE0F", "\u{1F445}", "\u{1F444}", "\u{1FAE6}", "\u{1F476}", "\u{1F9D2}",
    ],
  },
  {
    label: "Nature",
    emojis: [
      "\u{1F436}", "\u{1F431}", "\u{1F42D}", "\u{1F439}", "\u{1F430}", "\u{1F98A}",
      "\u{1F43B}", "\u{1F43C}", "\u{1F9A5}", "\u{1F428}", "\u{1F42F}", "\u{1F981}",
      "\u{1F434}", "\u{1F984}", "\u{1F42E}", "\u{1F437}", "\u{1F438}", "\u{1F435}",
      "\u{1F648}", "\u{1F649}", "\u{1F64A}", "\u{1F412}", "\u{1F414}", "\u{1F427}",
      "\u{1F426}", "\u{1F985}", "\u{1F9A2}", "\u{1F989}", "\u{1F9A9}", "\u{1F99A}",
      "\u{1F339}", "\u{1F33A}", "\u{1F33B}", "\u{1F33C}", "\u{1F337}", "\u{1FAB7}",
      "\u{1F332}", "\u{1F333}", "\u{1F334}", "\u{1F335}", "\u{1FAB4}", "\u{1F33F}",
      "\u{2618}\uFE0F", "\u{1F340}", "\u{1F341}", "\u{1F342}", "\u{1F343}", "\u{1FAB9}",
      "\u{1FABB}", "\u{1F490}", "\u{1F31F}", "\u{2B50}", "\u{1F31E}", "\u{1F31D}",
      "\u{1F308}", "\u{2600}\uFE0F", "\u{1F324}\uFE0F", "\u{26C5}", "\u{1F327}\uFE0F", "\u{26A1}",
    ],
  },
  {
    label: "Food",
    emojis: [
      "\u{1F34E}", "\u{1F34F}", "\u{1F350}", "\u{1F34A}", "\u{1F34B}", "\u{1F34C}",
      "\u{1F349}", "\u{1F347}", "\u{1F353}", "\u{1FAD0}", "\u{1F352}", "\u{1F351}",
      "\u{1F96D}", "\u{1F34D}", "\u{1F965}", "\u{1F95D}", "\u{1F345}", "\u{1F346}",
      "\u{1F951}", "\u{1F966}", "\u{1F96C}", "\u{1F952}", "\u{1F336}\uFE0F", "\u{1FAD1}",
      "\u{1F33D}", "\u{1F955}", "\u{1F9C4}", "\u{1F9C5}", "\u{1F954}", "\u{1F360}",
      "\u{1F950}", "\u{1F35E}", "\u{1F956}", "\u{1FAD3}", "\u{1F968}", "\u{1F96F}",
      "\u{1F9C0}", "\u{1F356}", "\u{1F357}", "\u{1F969}", "\u{1F354}", "\u{1F35F}",
      "\u{1F355}", "\u{1F32D}", "\u{1F96A}", "\u{1F32E}", "\u{1F32F}", "\u{1FAD4}",
      "\u{1F959}", "\u{1F9C6}", "\u{1F958}", "\u{1F35D}", "\u{1F96B}", "\u{1F963}",
      "\u{1F957}", "\u{1F364}", "\u{1F371}", "\u{1F370}", "\u{1F382}", "\u{2615}",
    ],
  },
  {
    label: "Travel",
    emojis: [
      "\u{1F697}", "\u{1F695}", "\u{1F699}", "\u{1F68C}", "\u{1F3CE}\uFE0F", "\u{1F6F5}",
      "\u{1F6B2}", "\u{1F6F4}", "\u{1F6F9}", "\u{1F6FC}", "\u{1F691}", "\u{1F692}",
      "\u{1F693}", "\u{1F6A8}", "\u{1F680}", "\u{1F6F8}", "\u{2708}\uFE0F", "\u{1F6A2}",
      "\u{1F3E0}", "\u{1F3E2}", "\u{1F3E5}", "\u{1F3EB}", "\u{1F3ED}", "\u{1F3F0}",
      "\u{26EA}", "\u{1F54C}", "\u{1F3D4}\uFE0F", "\u{1F3D6}\uFE0F", "\u{1F3DD}\uFE0F", "\u{1F3DE}\uFE0F",
      "\u{1F30D}", "\u{1F30E}", "\u{1F30F}", "\u{1F5FA}\uFE0F", "\u{1F9ED}", "\u{26F0}\uFE0F",
      "\u{1F30B}", "\u{1F5FB}", "\u{26F2}", "\u{26F5}", "\u{1F3A2}", "\u{1F3A1}",
    ],
  },
  {
    label: "Activities",
    emojis: [
      "\u{26BD}", "\u{1F3C0}", "\u{1F3C8}", "\u{26BE}", "\u{1F94E}", "\u{1F3BE}",
      "\u{1F3D0}", "\u{1F3C9}", "\u{1F94F}", "\u{1F3B1}", "\u{1F3D3}", "\u{1F3F8}",
      "\u{1F94D}", "\u{1F3D2}", "\u{1F3D1}", "\u{1F945}", "\u{26F3}", "\u{1F3AF}",
      "\u{1F3AE}", "\u{1F3B2}", "\u{1F9E9}", "\u{265F}\uFE0F", "\u{1F3A8}", "\u{1F3AD}",
      "\u{1F3B5}", "\u{1F3B6}", "\u{1F3B9}", "\u{1F941}", "\u{1F3B7}", "\u{1F3BA}",
      "\u{1F3B8}", "\u{1F3BB}", "\u{1FA98}", "\u{1FA95}", "\u{1F3AC}", "\u{1F4F7}",
      "\u{1F3C6}", "\u{1F3C5}", "\u{1F947}", "\u{1F948}", "\u{1F949}", "\u{1F396}\uFE0F",
    ],
  },
  {
    label: "Objects",
    emojis: [
      "\u{1F4D6}", "\u{1F4DA}", "\u{1F4D3}", "\u{1F4D2}", "\u{1F4C4}", "\u{1F4DD}",
      "\u{1F4CC}", "\u{1F4CE}", "\u{1F587}\uFE0F", "\u{1F4CB}", "\u{1F4C1}", "\u{1F4C2}",
      "\u{1F4C5}", "\u{1F4C6}", "\u{1F4C8}", "\u{1F4C9}", "\u{1F4CA}", "\u{1F4E7}",
      "\u{1F4E8}", "\u{1F4E9}", "\u{1F4E4}", "\u{1F4E5}", "\u{1F4E6}", "\u{1F4EB}",
      "\u{1F4F0}", "\u{1F4BB}", "\u{1F5A5}\uFE0F", "\u{2328}\uFE0F", "\u{1F5B1}\uFE0F", "\u{1F4F1}",
      "\u{260E}\uFE0F", "\u{1F50B}", "\u{1F50C}", "\u{1F4A1}", "\u{1F526}", "\u{1F56F}\uFE0F",
      "\u{1F5D1}\uFE0F", "\u{1F6D2}", "\u{1F4B0}", "\u{1F4B3}", "\u{1F4B5}", "\u{1F48E}",
      "\u{1F511}", "\u{1F5DD}\uFE0F", "\u{1F512}", "\u{1F513}", "\u{1F528}", "\u{1FA9B}",
      "\u{1F6E0}\uFE0F", "\u{1F527}", "\u{2699}\uFE0F", "\u{1F9F2}", "\u{1F52C}", "\u{1F52D}",
      "\u{1F4E1}", "\u{1F489}", "\u{1FA79}", "\u{1FA7A}", "\u{1F321}\uFE0F", "\u{2696}\uFE0F",
    ],
  },
  {
    label: "Symbols",
    emojis: [
      "\u{2764}\uFE0F", "\u{1F9E1}", "\u{1F49B}", "\u{1F49A}", "\u{1F499}", "\u{1F49C}",
      "\u{1F5A4}", "\u{1FA76}", "\u{1FA75}", "\u{1FA77}", "\u{1F90D}", "\u{1F90E}",
      "\u{2763}\uFE0F", "\u{1F495}", "\u{1F49E}", "\u{1F493}", "\u{1F497}", "\u{1F496}",
      "\u{1F498}", "\u{1F49D}", "\u{1F48C}", "\u{1F4AF}", "\u{1F4A2}", "\u{1F4A5}",
      "\u{1F4AB}", "\u{1F4A6}", "\u{2728}", "\u{1F525}", "\u{1F4A8}", "\u{1F573}\uFE0F",
      "\u{2705}", "\u{274C}", "\u{274E}", "\u{2B55}", "\u{26D4}", "\u{1F6AB}",
      "\u{26A0}\uFE0F", "\u{2757}", "\u{2753}", "\u{2755}", "\u{1F198}", "\u{1F4F4}",
      "\u{1F503}", "\u{1F504}", "\u{1F519}", "\u{1F51A}", "\u{1F51B}", "\u{1F51C}",
      "\u{1F6D1}", "\u{267B}\uFE0F", "\u{269B}\uFE0F", "\u{1F52F}", "\u{1F3B4}", "\u{1F0CF}",
    ],
  },
  {
    label: "Flags",
    emojis: [
      "\u{1F3C1}", "\u{1F6A9}", "\u{1F38C}", "\u{1F3F4}", "\u{1F3F3}\uFE0F",
      "\u{1F1FA}\u{1F1F8}", "\u{1F1EC}\u{1F1E7}", "\u{1F1EF}\u{1F1F5}", "\u{1F1EB}\u{1F1F7}", "\u{1F1E9}\u{1F1EA}",
      "\u{1F1E8}\u{1F1E6}", "\u{1F1E6}\u{1F1FA}", "\u{1F1E7}\u{1F1F7}", "\u{1F1F0}\u{1F1F7}", "\u{1F1EE}\u{1F1F3}",
      "\u{1F1EE}\u{1F1F9}", "\u{1F1EA}\u{1F1F8}", "\u{1F1F2}\u{1F1FD}", "\u{1F1F5}\u{1F1ED}", "\u{1F1F7}\u{1F1FA}",
    ],
  },
];

// --- Emoji search labels (for filter matching) ---

const EMOJI_SEARCH_LABELS: Record<string, string[]> = {
  Smileys: ["smile", "happy", "laugh", "face", "grin", "wink", "love", "cool", "nerd", "think", "sad", "cry", "sleep", "sick"],
  People: ["hand", "wave", "thumbs", "clap", "point", "fist", "pray", "muscle", "brain", "eye", "finger", "ok"],
  Nature: ["dog", "cat", "animal", "flower", "tree", "plant", "sun", "moon", "rainbow", "star", "weather", "rain", "snow"],
  Food: ["fruit", "vegetable", "meat", "bread", "pizza", "burger", "cake", "coffee", "drink", "food", "eat", "cook"],
  Travel: ["car", "plane", "rocket", "house", "building", "city", "mountain", "beach", "map", "world", "earth"],
  Activities: ["sport", "ball", "game", "music", "art", "trophy", "medal", "win", "play", "guitar", "movie"],
  Objects: ["book", "pen", "paper", "computer", "phone", "light", "key", "lock", "tool", "money", "mail", "folder"],
  Symbols: ["heart", "love", "check", "cross", "warning", "star", "fire", "sparkle", "circle", "arrow", "stop"],
  Flags: ["flag", "country", "nation", "usa", "uk", "japan", "france", "germany", "canada", "brazil", "korea", "india", "philippines"],
};

export function searchEmojis(query: string): typeof EMOJI_DATA {
  if (!query.trim()) return EMOJI_DATA;
  const q = query.toLowerCase();
  return EMOJI_DATA.map((category) => {
    const labels = EMOJI_SEARCH_LABELS[category.label] ?? [];
    const categoryMatches = category.label.toLowerCase().includes(q) || labels.some((l) => l.includes(q));
    if (categoryMatches) return category;
    return { ...category, emojis: [] };
  }).filter((c) => c.emojis.length > 0);
}

export function searchLucideIcons(query: string): typeof LUCIDE_ICON_CATEGORIES {
  if (!query.trim()) return LUCIDE_ICON_CATEGORIES;
  const q = query.toLowerCase();
  return LUCIDE_ICON_CATEGORIES.map((category) => {
    const filteredIcons = category.icons.filter((name) =>
      name.toLowerCase().includes(q) || name.replace(/-/g, " ").includes(q)
    );
    return { ...category, icons: filteredIcons };
  }).filter((c) => c.icons.length > 0);
}
